// <auto-generated />
namespace Test_Adneom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateBoissonInUtilisateursTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateBoissonInUtilisateursTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802151712345_updateBoissonInUtilisateursTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
